# Generated by Django 5.0.6 on 2024-06-07 10:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(choices=[('Mpesa', 'Mpesa'), ('Cash', 'Cash'), ('Bank', 'Bank')], default='Cash', max_length=15)),
                ('expense_category', models.CharField(choices=[('Car', 'Car'), ('Bills', 'Bills'), ('Education', 'Education'), ('Health', 'Health'), ('Shopping', 'Shopping'), ('Transport', 'Transport'), ('WiFi', 'WiFi')], default='Car', max_length=15)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('expense_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
