# Generated by Django 5.0.6 on 2024-06-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='transaction_type',
            field=models.CharField(choices=[('Expense', 'Expense'), ('Income', 'Income'), ('Transfer', 'Transfer')], default='Expense', max_length=15),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='account',
            field=models.CharField(choices=[('Mpesa', 'Mpesa'), ('Cash', 'Cash'), ('Bank', 'Bank'), ('Crypto', 'Crypto')], default='Cash', max_length=15),
        ),
    ]
