# Generated by Django 5.1 on 2024-09-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbalance',
            name='account',
            field=models.CharField(choices=[('Mpesa', 'Mpesa'), ('AirtelMoney', 'AirtelMoney'), ('Cash', 'Cash'), ('Bank', 'Bank'), ('CryptoWallet', 'CryptoWallet'), ('Savings', 'Savings'), ('MoneyMarketFund', 'MoneyMarketFund'), ('PayPal', 'PayPal')], default='Cash', max_length=15),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='account',
            field=models.CharField(choices=[('Mpesa', 'Mpesa'), ('AirtelMoney', 'AirtelMoney'), ('Cash', 'Cash'), ('Bank', 'Bank'), ('CryptoWallet', 'CryptoWallet'), ('Savings', 'Savings'), ('MoneyMarketFund', 'MoneyMarketFund'), ('PayPal', 'PayPal')], default='Cash', max_length=15),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='category',
            field=models.CharField(choices=[('CarBills', 'CarBills'), ('Bills', 'Bills'), ('Morgage/Rent', 'Morgage/Rent'), ('Education', 'Education'), ('Health', 'Health'), ('LoanPayments', 'LoanPayments'), ('Shopping', 'Shopping'), ('Transport', 'Transport'), ('WiFi', 'WiFi'), ('Subscriptions', 'Subscriptions'), ('Debt', 'Debt'), ('Clothing', 'Clothing')], default='Car', max_length=15),
        ),
        migrations.AlterField(
            model_name='income',
            name='account',
            field=models.CharField(choices=[('Mpesa', 'Mpesa'), ('AirtelMoney', 'AirtelMoney'), ('Cash', 'Cash'), ('Bank', 'Bank'), ('CryptoWallet', 'CryptoWallet'), ('Savings', 'Savings'), ('MoneyMarketFund', 'MoneyMarketFund'), ('PayPal', 'PayPal')], default='Cash', max_length=15),
        ),
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.CharField(choices=[('Salary', 'Salary'), ('PocketMoney/Allowance', 'PocketMoney/Allowance'), ('Investments', 'Investments'), ('Lotery', 'Lotery'), ('Grants', 'Grants'), ('Gifts', 'Gifts'), ('RentalIncome', 'RentalIncome')], default='Salary', max_length=30),
        ),
    ]
