# Generated by Django 5.1 on 2024-09-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_accountbalance_account_alter_expenses_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbalance',
            name='account',
            field=models.CharField(choices=[('Mpesa', 'Mpesa'), ('AirtelMoney', 'AirtelMoney'), ('Cash', 'Cash'), ('Bank', 'Bank'), ('CryptoWallet', 'CryptoWallet'), ('Savings', 'Savings'), ('MoneyMarketFund', 'MoneyMarketFund'), ('PayPal', 'PayPal'), ('Other', 'Other')], default='Cash', max_length=15),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='account',
            field=models.CharField(choices=[('Mpesa', 'Mpesa'), ('AirtelMoney', 'AirtelMoney'), ('Cash', 'Cash'), ('Bank', 'Bank'), ('CryptoWallet', 'CryptoWallet'), ('Savings', 'Savings'), ('MoneyMarketFund', 'MoneyMarketFund'), ('PayPal', 'PayPal'), ('Other', 'Other')], default='Cash', max_length=15),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='category',
            field=models.CharField(choices=[('CarBills', 'CarBills'), ('Subscriptions', 'Subscriptions'), ('Bills/Utilities', 'Bills/Utilities'), ('Morgage/Rent', 'Morgage/Rent'), ('Education', 'Education'), ('MedicalCare', 'MedicalCare'), ('LoanPayments', 'LoanPayments'), ('Shopping', 'Shopping'), ('Transport', 'Transport'), ('WiFi', 'WiFi'), ('Clothing', 'Clothing'), ('Others', 'Others')], default='Car', max_length=15),
        ),
        migrations.AlterField(
            model_name='income',
            name='account',
            field=models.CharField(choices=[('Mpesa', 'Mpesa'), ('AirtelMoney', 'AirtelMoney'), ('Cash', 'Cash'), ('Bank', 'Bank'), ('CryptoWallet', 'CryptoWallet'), ('Savings', 'Savings'), ('MoneyMarketFund', 'MoneyMarketFund'), ('PayPal', 'PayPal'), ('Other', 'Other')], default='Cash', max_length=15),
        ),
    ]
