# Generated by Django 5.0.6 on 2024-06-08 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_expenses_transaction_type_alter_expenses_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenses',
            options={'ordering': ['-date_added']},
        ),
    ]
