# Generated by Django 5.1 on 2024-09-13 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_accountbalance_account_alter_expenses_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='from_account',
            field=models.CharField(choices=[('Mpesa', 'Mpesa'), ('AirtelMoney', 'AirtelMoney'), ('Cash', 'Cash'), ('Bank', 'Bank'), ('CryptoWallet', 'CryptoWallet'), ('Savings', 'Savings'), ('MoneyMarketFund', 'MoneyMarketFund'), ('PayPal', 'PayPal'), ('Other', 'Other')], default='Mpesa', max_length=15),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='to_account',
            field=models.CharField(choices=[('Mpesa', 'Mpesa'), ('AirtelMoney', 'AirtelMoney'), ('Cash', 'Cash'), ('Bank', 'Bank'), ('CryptoWallet', 'CryptoWallet'), ('Savings', 'Savings'), ('MoneyMarketFund', 'MoneyMarketFund'), ('PayPal', 'PayPal'), ('Other', 'Other')], default='Cash', max_length=15),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startingbalance', models.DecimalField(decimal_places=2, default=0, max_digits=90)),
                ('denomination', models.CharField(max_length=255)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
