# Generated by Django 5.0.6 on 2024-06-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_expenses_income_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='income_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
