# Generated by Django 5.1 on 2024-09-20 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_transfer_from_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbalance',
            name='startingbalance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
