# Generated by Django 5.1 on 2024-09-23 06:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_accountbalance_startingbalance_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbalance',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
