# Generated by Django 5.0.6 on 2024-08-04 15:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_expense_amount_expenses_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Transfer', 'Transfer')], default='Income', max_length=15)),
                ('from_account', models.CharField(choices=[('Mpesa', 'Mpesa'), ('Cash', 'Cash'), ('Bank', 'Bank'), ('Crypto', 'Crypto')], default='Mpesa', max_length=15)),
                ('to_account', models.CharField(choices=[('Mpesa', 'Mpesa'), ('Cash', 'Cash'), ('Bank', 'Bank'), ('Crypto', 'Crypto')], default='Cash', max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
