# Generated by Django 5.1 on 2024-09-26 08:21

import datetime
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_income_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today)]),
        ),
    ]
