# Generated by Django 5.1 on 2024-09-26 08:24

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_income_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, validators=[django.core.validators.MaxValueValidator(limit_value=django.utils.timezone.now)]),
        ),
    ]
