# Generated by Django 5.1 on 2024-09-26 08:33

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_expenses_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbalance',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, validators=[django.core.validators.MaxValueValidator(limit_value=django.utils.timezone.now)]),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, validators=[django.core.validators.MaxValueValidator(limit_value=django.utils.timezone.now)]),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, validators=[django.core.validators.MaxValueValidator(limit_value=django.utils.timezone.now)]),
        ),
    ]
